name: Continuous Build

on:
  push:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  require-changeset:
    name: Require a changeset
    runs-on: ubuntu-latest
    steps:
      - name: Clone airnode
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'
      - name: restore lerna
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn run bootstrap
      - name: Build
        run: yarn run build
      - name: Require a changeset
        # https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#responding-to-events
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        run: |
          git pull -f origin master:master
          yarn check-changeset

  build-complete:
    name: All tests passed
    runs-on: ubuntu-latest
    needs: [require-changeset]
    steps:
      - run: exit 0
